-- ============================================
-- WORDS TABLE SEED
-- 150 curated words for the 30-second game
-- Focused on articulation, rhetoric, communication, and critical thinking
-- No overlap with vocabularyData.js existing words
-- Run once in Supabase SQL editor
-- ============================================

INSERT INTO public.words (word, definition, difficulty, synonyms, antonyms) VALUES

-- DIFFICULTY 1 (everyday vocabulary)
('amiable',      'Having a friendly and pleasant manner',                                              1, ARRAY['friendly','genial','affable','pleasant'],         ARRAY['hostile','unfriendly','cold','disagreeable']),
('blunt',        'Speaking in a direct and honest way without worrying about hurting feelings',        1, ARRAY['direct','forthright','candid','frank'],           ARRAY['tactful','diplomatic','subtle','evasive']),
('bold',         'Showing a willingness to take risks or face challenges with confidence',             1, ARRAY['daring','brave','confident','audacious'],         ARRAY['timid','cautious','meek','cowardly']),
('brief',        'Short in duration or using few words',                                              1, ARRAY['concise','short','succinct','terse'],             ARRAY['lengthy','verbose','prolonged','wordy']),
('calm',         'Not showing or feeling nervousness or anxiety; serene',                             1, ARRAY['serene','composed','tranquil','placid'],          ARRAY['agitated','anxious','turbulent','frantic']),
('curious',      'Eager to know or learn something new',                                              1, ARRAY['inquisitive','interested','eager','questioning'],  ARRAY['indifferent','apathetic','uninterested','incurious']),
('earnest',      'Showing sincere and intense conviction in what one says or does',                   1, ARRAY['sincere','genuine','serious','heartfelt'],        ARRAY['insincere','flippant','halfhearted','casual']),
('fluent',       'Able to express oneself easily and accurately in speech or writing',                1, ARRAY['articulate','smooth','natural','effortless'],     ARRAY['halting','hesitant','stumbling','awkward']),
('frank',        'Open, honest, and direct in speech or writing',                                    1, ARRAY['candid','direct','straightforward','open'],       ARRAY['evasive','dishonest','deceptive','guarded']),
('keen',         'Having a sharp or penetrating quality of mind; eager and enthusiastic',             1, ARRAY['sharp','astute','eager','perceptive'],            ARRAY['dull','indifferent','obtuse','apathetic']),
('loyal',        'Giving firm and constant support to a person, cause, or belief',                   1, ARRAY['faithful','devoted','steadfast','dedicated'],     ARRAY['disloyal','treacherous','faithless','fickle']),
('modest',       'Unassuming in the estimation of one''s abilities or achievements',                  1, ARRAY['humble','unassuming','reserved','unpretentious'], ARRAY['arrogant','boastful','conceited','vain']),
('prompt',       'Done without delay; quick to act or respond',                                      1, ARRAY['timely','quick','swift','punctual'],              ARRAY['late','slow','tardy','delayed']),
('reliable',     'Consistently good in quality or performance; dependable',                          1, ARRAY['dependable','trustworthy','consistent','steady'],  ARRAY['unreliable','erratic','undependable','inconsistent']),
('sincere',      'Free from pretense or deceit; proceeding from genuine feelings',                   1, ARRAY['genuine','honest','authentic','heartfelt'],       ARRAY['insincere','fake','hypocritical','deceitful']),

-- DIFFICULTY 2 (intermediate vocabulary)
('adamant',      'Refusing to be persuaded or to change one''s mind',                                2, ARRAY['firm','unyielding','resolute','steadfast'],       ARRAY['flexible','yielding','compliant','wavering']),
('adept',        'Very skilled or proficient at something',                                          2, ARRAY['skilled','expert','proficient','capable'],        ARRAY['inept','unskilled','incompetent','clumsy']),
('affable',      'Friendly, good-natured, and easy to talk to',                                     2, ARRAY['friendly','genial','amiable','sociable'],         ARRAY['aloof','cold','unfriendly','standoffish']),
('allude',       'To suggest or call attention to something indirectly',                             2, ARRAY['hint','suggest','imply','insinuate'],             ARRAY['declare','state','announce','proclaim']),
('altruistic',   'Showing a selfless concern for the well-being of others',                          2, ARRAY['selfless','generous','benevolent','charitable'],   ARRAY['selfish','self-centered','greedy','egotistic']),
('ambivalent',   'Having mixed feelings or contradictory ideas about something',                     2, ARRAY['uncertain','conflicted','undecided','torn'],      ARRAY['certain','decisive','resolute','committed']),
('apt',          'Appropriate or suitable in the circumstances; having a tendency to',               2, ARRAY['fitting','appropriate','suitable','relevant'],    ARRAY['inappropriate','unsuitable','inapt','irrelevant']),
('articulate',   'Having or showing the ability to speak fluently and coherently',                   2, ARRAY['eloquent','fluent','expressive','clear'],         ARRAY['inarticulate','tongue-tied','incoherent','mumbling']),
('astute',       'Having an ability to accurately assess situations and turn them to one''s advantage', 2, ARRAY['shrewd','sharp','perceptive','clever'],        ARRAY['naive','obtuse','gullible','foolish']),
('averse',       'Having a strong dislike of or opposition to something',                            2, ARRAY['opposed','reluctant','unwilling','resistant'],    ARRAY['eager','willing','enthusiastic','receptive']),
('cogent',       'Clear, logical, and convincing',                                                   2, ARRAY['convincing','persuasive','compelling','logical'],  ARRAY['weak','unconvincing','illogical','flawed']),
('condescend',   'To act in a way that implies one is superior; to talk down to someone',            2, ARRAY['patronize','belittle','demean','disparage'],      ARRAY['respect','uplift','esteem','honor']),
('contemplate',  'To think deeply and at length about something',                                    2, ARRAY['ponder','reflect','consider','deliberate'],       ARRAY['ignore','dismiss','overlook','disregard']),
('credible',     'Able to be believed; convincing and trustworthy',                                  2, ARRAY['believable','plausible','reliable','trustworthy'], ARRAY['incredible','unbelievable','dubious','implausible']),
('cultivate',    'To try to develop or improve a skill, feeling, or relationship',                   2, ARRAY['develop','foster','nurture','build'],             ARRAY['neglect','ignore','abandon','suppress']),
('defer',        'To put off an action to a later time; to yield to another''s opinion',             2, ARRAY['postpone','yield','submit','comply'],             ARRAY['resist','oppose','defy','persist']),
('demeanor',     'Outward behavior or bearing toward others',                                        2, ARRAY['manner','bearing','conduct','attitude'],          ARRAY['rudeness','impropriety','disrespect','insolence']),
('diligent',     'Having or showing care and conscientiousness in work or duties',                   2, ARRAY['hardworking','industrious','assiduous','thorough'], ARRAY['lazy','negligent','careless','idle']),
('discerning',   'Having or showing good judgment and understanding',                                2, ARRAY['perceptive','astute','judicious','insightful'],   ARRAY['undiscerning','careless','unobservant','obtuse']),
('dissent',      'To hold or express opinions that are at odds with an official or widely held view',2, ARRAY['disagree','oppose','object','protest'],           ARRAY['agree','consent','comply','conform']),
('dubious',      'Hesitating or doubting; not to be relied upon; suspect',                           2, ARRAY['doubtful','uncertain','questionable','skeptical'],ARRAY['certain','reliable','trustworthy','credible']),
('dynamic',      'Characterized by constant change, activity, or progress',                         2, ARRAY['energetic','vigorous','active','forceful'],       ARRAY['static','stagnant','passive','inert']),
('elicit',       'To draw out a response, answer, or reaction from someone',                        2, ARRAY['draw out','evoke','extract','provoke'],           ARRAY['suppress','stifle','repress','discourage']),
('emulate',      'To try to match or surpass by imitation; to model oneself on',                    2, ARRAY['imitate','follow','mirror','model'  ],            ARRAY['ignore','reject','avoid','differ']),
('engross',      'To absorb all the attention or interest of someone completely',                    2, ARRAY['absorb','captivate','engage','immerse'],          ARRAY['bore','repel','distract','disinterest']),

-- DIFFICULTY 3 (upper-intermediate vocabulary)
('abate',        'To become less intense, widespread, or severe',                                    3, ARRAY['diminish','subside','decrease','lessen'],         ARRAY['increase','intensify','grow','escalate']),
('acquiesce',    'To accept something reluctantly but without protest',                              3, ARRAY['comply','consent','submit','concede'],            ARRAY['resist','oppose','refuse','protest']),
('admonish',     'To warn or reprimand someone firmly',                                              3, ARRAY['warn','rebuke','caution','reproach'],             ARRAY['praise','commend','applaud','encourage']),
('adversarial',  'Involving opposition or conflict; acting against each other',                      3, ARRAY['hostile','opposing','antagonistic','combative'],  ARRAY['cooperative','collaborative','allied','amicable']),
('advocate',     'To publicly recommend or support a particular cause or policy',                    3, ARRAY['support','champion','promote','endorse'],         ARRAY['oppose','criticize','discourage','undermine']),
('alacrity',     'Brisk and cheerful readiness to do something',                                    3, ARRAY['eagerness','enthusiasm','willingness','zeal'],    ARRAY['reluctance','hesitation','unwillingness','apathy']),
('allegory',     'A story with a hidden meaning, typically a moral or political one',               3, ARRAY['metaphor','parable','fable','symbol'],            ARRAY['literal','explicit','direct','plain']),
('allusion',     'An indirect or passing reference to something',                                   3, ARRAY['reference','hint','suggestion','intimation'],     ARRAY['statement','declaration','assertion','proclamation']),
('anachronism',  'Something placed in the wrong time period; out of date',                          3, ARRAY['anomaly','incongruity','oddity','mismatch'],      ARRAY['contemporary','timely','current','modern']),
('anecdote',     'A short amusing or interesting account of a real incident',                       3, ARRAY['story','tale','account','narrative'],             ARRAY['theory','hypothesis','abstraction','generalization']),
('antagonize',   'To cause someone to become hostile',                                              3, ARRAY['provoke','irritate','alienate','offend'],         ARRAY['appease','placate','conciliate','soothe']),
('appease',      'To calm or placate someone by meeting their demands',                             3, ARRAY['pacify','placate','satisfy','conciliate'],        ARRAY['antagonize','provoke','anger','aggravate']),
('arbitrate',    'To reach an authoritative judgment or decision about a problem',                  3, ARRAY['mediate','judge','adjudicate','decide'],          ARRAY['dispute','contest','argue','quarrel']),
('assert',       'To state a fact or belief confidently and forcefully',                             3, ARRAY['declare','maintain','claim','affirm'],            ARRAY['deny','retract','withdraw','recant']),
('brevity',      'Concise and exact use of words in writing or speech',                             3, ARRAY['conciseness','terseness','succinctness','economy'], ARRAY['verbosity','wordiness','prolixity','length']),
('catalyst',     'A person or thing that precipitates an event or change',                          3, ARRAY['trigger','stimulus','spark','impetus'],           ARRAY['deterrent','hindrance','obstacle','impediment']),
('circumspect',  'Wary and unwilling to take risks; careful to consider consequences',              3, ARRAY['cautious','prudent','careful','wary'],            ARRAY['reckless','impulsive','careless','rash']),
('coerce',       'To persuade an unwilling person to do something by using force or threats',       3, ARRAY['compel','force','pressure','intimidate'],         ARRAY['persuade','encourage','invite','allow']),
('coherent',     'Logical and consistent; easy to understand',                                      3, ARRAY['logical','consistent','clear','intelligible'],    ARRAY['incoherent','confused','muddled','inconsistent']),
('collaborate',  'To work jointly on an activity or project',                                       3, ARRAY['cooperate','partner','join','teamwork'],          ARRAY['compete','oppose','conflict','hinder']),
('concede',      'To admit that something is true after initially denying it',                      3, ARRAY['admit','acknowledge','yield','grant'],            ARRAY['deny','dispute','contest','refuse']),
('convoluted',   'Extremely complex and difficult to follow',                                       3, ARRAY['complicated','intricate','complex','tangled'],    ARRAY['simple','clear','straightforward','uncomplicated']),
('credence',     'Belief in or acceptance of something as true',                                    3, ARRAY['belief','trust','faith','acceptance'],            ARRAY['disbelief','doubt','skepticism','distrust']),
('critique',     'A detailed analysis and assessment of something',                                 3, ARRAY['analysis','evaluation','assessment','review'],    ARRAY['praise','approval','endorsement','commendation']),
('cunning',      'Having or showing skill in achieving one''s ends by deceit',                      3, ARRAY['crafty','shrewd','sly','clever'],                 ARRAY['naive','honest','straightforward','guileless']),
('debunk',       'To expose the falseness or hollowness of an idea or belief',                      3, ARRAY['disprove','refute','expose','discredit'],         ARRAY['confirm','validate','support','substantiate']),
('deflect',      'To cause something to change direction; to turn aside criticism',                 3, ARRAY['divert','redirect','turn','avert'],               ARRAY['face','confront','address','engage']),
('deliberate',   'Done consciously and intentionally; slow and careful',                            3, ARRAY['intentional','calculated','measured','careful'],  ARRAY['accidental','hasty','careless','impulsive']),
('disingenuous', 'Not candid or sincere; pretending to be ignorant of something',                  3, ARRAY['insincere','dishonest','deceptive','misleading'],  ARRAY['sincere','honest','candid','genuine']),

-- DIFFICULTY 4 (advanced vocabulary)
('abrogate',     'To repeal or do away with a law, right, or formal agreement',                     4, ARRAY['abolish','annul','repeal','revoke'],              ARRAY['establish','enact','uphold','ratify']),
('acrimonious',  'Angry and bitter, especially in speech or manner',                                4, ARRAY['bitter','hostile','caustic','sharp'],             ARRAY['amicable','pleasant','cordial','agreeable']),
('adumbrate',    'To give a sketchy outline or foreshadow something',                               4, ARRAY['outline','sketch','foreshadow','suggest'],        ARRAY['detail','elaborate','explain','clarify']),
('animus',       'Hostility or ill feeling; the motivation behind an action',                       4, ARRAY['hostility','enmity','ill will','antipathy'],      ARRAY['goodwill','benevolence','friendliness','amity']),
('apotheosis',   'The highest point in the development of something; the perfect form',             4, ARRAY['pinnacle','peak','height','ideal'],               ARRAY['nadir','lowest','worst','bottom']),
('apposite',     'Apt in the circumstances or in relation to something; highly appropriate',        4, ARRAY['appropriate','fitting','relevant','pertinent'],   ARRAY['irrelevant','inappropriate','inapt','unsuitable']),
('approbation',  'Approval or praise, especially from an authority',                                4, ARRAY['approval','praise','endorsement','commendation'],  ARRAY['disapproval','condemnation','criticism','censure']),
('artful',       'Clever or skillful; using indirect methods to achieve something',                 4, ARRAY['clever','crafty','shrewd','ingenious'],           ARRAY['clumsy','naive','straightforward','blunt']),
('ascetic',      'Characterized by severe self-discipline and abstention from indulgence',          4, ARRAY['austere','spartan','self-denying','abstemious'],  ARRAY['indulgent','hedonistic','luxurious','self-indulgent']),
('assuage',      'To make an unpleasant feeling less intense; to soothe',                           4, ARRAY['soothe','ease','relieve','alleviate'],            ARRAY['aggravate','intensify','worsen','inflame']),
('attrition',    'The process of reducing something''s strength through sustained pressure',        4, ARRAY['erosion','wearing down','depletion','reduction'],  ARRAY['strengthening','building','growth','increase']),
('audacious',    'Showing a willingness to take surprisingly bold risks',                           4, ARRAY['daring','bold','fearless','enterprising'],        ARRAY['timid','cautious','cowardly','meek']),
('axiom',        'A statement or proposition regarded as self-evidently true',                      4, ARRAY['maxim','principle','truism','postulate'],         ARRAY['paradox','contradiction','fallacy','absurdity']),
('byzantine',    'Excessively complicated and difficult to understand',                             4, ARRAY['complex','convoluted','intricate','labyrinthine'], ARRAY['simple','straightforward','clear','direct']),
('cacophony',    'A harsh, discordant mixture of sounds',                                           4, ARRAY['discord','noise','din','clamor'],                 ARRAY['harmony','melody','euphony','concord']),
('calumny',      'The making of false and defamatory statements about someone',                     4, ARRAY['slander','defamation','libel','vilification'],    ARRAY['praise','commendation','flattery','acclaim']),
('capitulate',   'To cease to resist an opponent or an unwelcome demand; to give in',               4, ARRAY['surrender','yield','submit','concede'],           ARRAY['resist','persist','fight','hold out']),
('capricious',   'Given to sudden and unaccountable changes of mood or behavior',                   4, ARRAY['unpredictable','fickle','impulsive','erratic'],   ARRAY['consistent','predictable','steady','reliable']),
('caveat',       'A warning or proviso of specific stipulations or limitations',                    4, ARRAY['warning','caution','condition','qualification'],   ARRAY['assurance','guarantee','certainty','promise']),
('censure',      'To express severe disapproval of someone or something, especially formally',      4, ARRAY['condemn','criticize','rebuke','denounce'],        ARRAY['praise','commend','approve','endorse']),
('chicanery',    'The use of trickery to achieve a political or personal advantage',                4, ARRAY['deception','trickery','deceit','dishonesty'],     ARRAY['honesty','integrity','candor','sincerity']),
('circumlocution','The use of many words where fewer would do; evasive talk',                       4, ARRAY['verbosity','wordiness','periphrasis','evasion'],  ARRAY['brevity','conciseness','directness','succinctness']),
('clandestine',  'Kept secret or done secretively, especially because illicit',                    4, ARRAY['secret','covert','hidden','furtive'],             ARRAY['open','public','overt','transparent']),
('clemency',     'Mercy and leniency shown toward an offender',                                     4, ARRAY['mercy','leniency','compassion','forgiveness'],    ARRAY['harshness','severity','cruelty','strictness']),
('cogitate',     'To think deeply about something; to meditate or ponder',                         4, ARRAY['ponder','deliberate','reflect','contemplate'],    ARRAY['ignore','dismiss','overlook','react']),

-- DIFFICULTY 5 (expert vocabulary)
('abstruse',     'Difficult to understand; obscure',                                                5, ARRAY['obscure','arcane','recondite','incomprehensible'], ARRAY['clear','simple','straightforward','accessible']),
('adroit',       'Clever or skillful in using the hands or mind',                                   5, ARRAY['dexterous','skillful','expert','proficient'],     ARRAY['clumsy','inept','awkward','unskilled']),
('anodyne',      'Not likely to provoke dissent; intentionally inoffensive or bland',               5, ARRAY['bland','inoffensive','safe','neutral'],           ARRAY['provocative','controversial','offensive','bold']),
('aphorism',     'A pithy observation that contains a general truth',                               5, ARRAY['maxim','adage','proverb','saying'],               ARRAY['rambling','verbose','unclear','muddled']),
('apocryphal',   'Of doubtful authenticity, although widely circulated as true',                    5, ARRAY['dubious','questionable','mythical','fictional'],  ARRAY['authentic','genuine','verified','factual']),
('approbatory',  'Expressing approval or praise',                                                   5, ARRAY['approving','laudatory','complimentary','praising'], ARRAY['critical','disapproving','condemnatory','censorious']),
('atavistic',    'Relating to the reappearance of traits from remote ancestors',                    5, ARRAY['primitive','ancestral','ancient','primordial'],   ARRAY['modern','evolved','advanced','contemporary']),
('bathetic',     'Producing an effect of anticlimax, typically through over-sentimentality',        5, ARRAY['anticlimactic','mawkish','maudlin','trite'],      ARRAY['sublime','moving','profound','powerful']),
('canard',       'An unfounded rumor or story; a deliberately false report',                        5, ARRAY['rumor','fabrication','falsehood','hoax'],         ARRAY['truth','fact','reality','verified']),
('captious',     'Too ready to find fault; quick to point out flaws',                               5, ARRAY['faultfinding','critical','petty','nitpicking'],   ARRAY['approving','generous','lenient','fair']),
('chary',        'Cautiously or suspiciously reluctant to do something',                            5, ARRAY['cautious','wary','reluctant','guarded'],          ARRAY['reckless','bold','eager','impulsive']),
('compunction',  'A feeling of guilt or moral scruple about doing something wrong',                 5, ARRAY['remorse','guilt','regret','scruple'],             ARRAY['indifference','shamelessness','callousness','recklessness']),
('contentious',  'Causing or likely to cause an argument; controversial',                           5, ARRAY['controversial','disputed','debatable','divisive'], ARRAY['uncontroversial','agreeable','harmonious','settled']),
('contrite',     'Feeling or expressing remorse at the recognition of one''s wrongdoing',           5, ARRAY['remorseful','penitent','repentant','apologetic'],  ARRAY['impenitent','unremorseful','proud','unapologetic']),
('convivial',    'Friendly, lively, and enjoyable; relating to good company',                       5, ARRAY['sociable','genial','jovial','festive'],           ARRAY['unfriendly','unsociable','gloomy','dour']),
('corpulent',    'Excessively overweight or fat',                                                   5, ARRAY['obese','overweight','stout','rotund'],            ARRAY['slender','lean','thin','slim']),
('corrosive',    'Destructive to metal or other material by chemical action; tending to destroy',  5, ARRAY['destructive','caustic','erosive','damaging'],     ARRAY['protective','preserving','constructive','healing']),
('dilettante',   'A person who cultivates an area of interest without real commitment',             5, ARRAY['amateur','dabbler','layperson','novice'],         ARRAY['expert','professional','specialist','authority']),
('dissonance',   'Lack of harmony; a tension between conflicting elements',                         5, ARRAY['discord','conflict','tension','inconsistency'],   ARRAY['harmony','agreement','accord','consonance']),
('effrontery',   'Insolent or impertinent behavior; shameless boldness',                            5, ARRAY['audacity','impudence','insolence','nerve'],       ARRAY['humility','deference','meekness','modesty']),
('enervate',     'To cause someone to feel drained of energy or vitality',                          5, ARRAY['weaken','exhaust','debilitate','sap'],            ARRAY['invigorate','energize','strengthen','vitalize']),
('equivocate',   'To use ambiguous language so as to conceal the truth',                            5, ARRAY['hedge','evade','prevaricate','waffle'],           ARRAY['assert','declare','affirm','state clearly']),
('ersatz',       'Made or used as a substitute; artificial and inferior',                           5, ARRAY['artificial','fake','synthetic','substitute'],     ARRAY['genuine','authentic','real','original']),
('feckless',     'Lacking initiative or strength of character; irresponsible',                      5, ARRAY['irresponsible','weak','ineffective','worthless'],  ARRAY['responsible','capable','effective','strong']),
('garrulous',    'Excessively talkative, especially on trivial matters',                            5, ARRAY['talkative','verbose','loquacious','chatty'],      ARRAY['taciturn','quiet','reserved','concise']);
